printWidth = 180
trailingComma = "all"
tabWidth = 4
semi = true
singleQuote = true
bracketSpacing = true
bracketSameLine = true
arrowParens = "always"
htmlWhitespaceSensitivity = "strict"
singleAttributePerLine = false
